=== webresto/core/libs/schemas/settingsFile.json
{
  "$schema": "http://json-schema.org/draft-07/schema#",
  "type": "object",
  "properties": {
    "key": {
      "type": "string",
      "description": "The key identifier"
    },
    "type": {
      "type": "string",
      "enum": ["string", "boolean", "json", "number"],
      "description": "The type"
    },
    "name": {
      "type": "string",
      "description": "The name"
    },
    "description": {
      "type": "string",
      "description": "The description of the description."
    },
    "defaultValue": {
      "type": ["string", "boolean", "object", "number"],
      "description": "The default value"
    },
    "value": {
      "type": ["string", "boolean", "object", "number", "array"],
      "description": "The value"
    },
    "isRequired": {
      "type": "boolean",
      "description": "Specifies whether the description is required or not."
    },
    "jsonSchema": {
      "$ref": "http://json-schema.org/draft-07/schema#"
    }
  },
  "required": ["key", "type", "name"],
  "additionalProperties": false,
  "if": {
    "properties": {
      "type": { "const": "json" }
    }
  },
  "then": {
    "required": ["jsonSchema"]
  }
}

=== webresto/core/settings/password_policy.json
{
  "key": "PASSWORD_POLICY",
  "type": "string",
  "name": "Password Policy",
  "description": "Defines the password requirement policy for user accounts. The options are: 'required' (password must be set), 'from_otp' (password is generated from a one-time password), or 'disabled' (no password is required).",
  "defaultValue": "from_otp",
  "jsonSchema": {
    "type": "string",
    "enum": ["required", "from_otp", "disabled"]
  },
  "isRequired": true
}

=== webresto/core/settings/uuid_namespace.json
{
  "key": "UUID_NAMESPACE",
  "type": "string",
  "name": "UUID Namespace",
  "description": "Should be array-like (16 iterable integer values, 0-255)",
  "jsonSchema": {
    "type": "string",
    "pattern": "^[0-9a-f]{8}(-[0-9a-f]{4}){3}-[0-9a-f]{12}$",
    "minLength": 36,
    "maxLength": 36
  },
  "isRequired": true
}
